In [32]:
import pandas as pd

In [33]:
df = pd.read_csv('oi-receita.csv', encoding='ISO-8859-1', sep=';', decimal=',')
df

,Exercício,Grupo Cód.,Grupo,Cód. Empresa,Sigla Empresa,Fonte Mãe Código,Fonte Mãe,Fonte Cód.,Fonte,PLoa,...,Realizado até Mar,Realizado até Abr,Realizado até Mai,Realizado até Jun,Realizado até Jul,Realizado até Ago,Realizado até Set,Realizado até Out,Realizado até Nov,Realizado até Dez
0,2020,40,DEMAIS EMPRESAS DO SPE,22208,Ceasaminas,61000000,Recursos Próprios,61100000,Geração Própria,1.750.000,...,20.160,20.160,20.160,33.722,37.712,37.712,71.612,85.471,168.277,205.282
1,2020,40,DEMAIS EMPRESAS DO SPE,22212,Ceagesp,61000000,Recursos Próprios,61100000,Geração Própria,12.510.802,...,35.223,47.047,108.367,141.126,141.906,152.796,158.146,201.548,224.756,224.756
2,2020,40,DEMAIS EMPRESAS DO SPE,24214,ECT,61000000,Recursos Próprios,61100000,Geração Própria,833.217.388,...,31.128,31.128,3.332.926,22.744.380,34.779.310,64.087.012,115.074.897,136.753.112,198.161.813,316.856.867
3,2020,40,DEMAIS EMPRESAS DO SPE,24214,ECT,62000000,Recursos Para Aumento Do Patrimonio Liquido,62130000,Saldos de Exercícios Anteriores,0,...,15.083.755,19.222.965,20.944.074,20.944.074,20.944.074,20.944.074,20.944.074,20.944.074,20.944.074,20.944.074
4,2020,40,DEMAIS EMPRESAS DO SPE,25207,Serpro,61000000,Recursos Próprios,61100000,Geração Própria,210.000.000,...,8.556.248,8.954.446,8.954.446,9.873.340,13.372.887,14.276.781,22.906.048,46.151.884,80.115.475,169.775.143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2020,30,GRUPO PETROBRAS,32334,Pbio,61000000,Recursos Próprios,61100000,Geração Própria,16.749.000,...,1.534.725,1.916.501,2.321.481,2.749.066,3.367.532,3.803.858,4.416.759,5.061.235,5.834.035,6.610.361
96,2020,30,GRUPO PETROBRAS,32346,Mangue Seco 2,61000000,Recursos Próprios,61100000,Geração Própria,68.000,...,0,0,0,2.134,2.134,2.134,2.134,2.134,43.885,43.885
97,2020,30,GRUPO PETROBRAS,32367,Araucária,61000000,Recursos Próprios,61100000,Geração Própria,107.364.406,...,0,0,0,0,0,0,0,0,0,0
98,2020,30,GRUPO PETROBRAS,32370,TI B.V.,61000000,Recursos Próprios,61100000,Geração Própria,32.667.000,...,1.033.125,1.152.768,1.595.389,1.993.916,2.702.447,3.967.301,4.339.326,4.404.028,4.637.535,5.197.428
99,2020,30,GRUPO PETROBRAS,32903,-,61000000,Recursos Próprios,61100000,Geração Própria,0,...,0,0,0,0,0,0,0,0,0,0

In [34]:
#Ver o tipo
df.dtypes

Exercício             int64
Grupo Cód.            int64
Grupo                object
Cód. Empresa          int64
Sigla Empresa        object
Fonte Mãe Código      int64
Fonte Mãe            object
Fonte Cód.            int64
Fonte                object
PLoa                 object
Loa                  object
LOA + Crédito        object
Realizado até Jan    object
Realizado até Fev    object
Realizado até Mar    object
Realizado até Abr    object
Realizado até Mai    object
Realizado até Jun    object
Realizado até Jul    object
Realizado até Ago    object
Realizado até Set    object
Realizado até Out    object
Realizado até Nov    object
Realizado até Dez    object
dtype: object

In [5]:
#Transformando dtype em int
df['Grupo Cód.'] = df['Grupo Cód.'].astype(int)

In [6]:
pd.to_numeric(df['Exercício'])

0     2020
1     2020
2     2020
3     2020
4     2020
      ...
95    2020
96    2020
97    2020
98    2020
99    2020
Name: Exercício, Length: 100, dtype: int64

In [3]:
df['Exercício']

0     2020
1     2020
2     2020
3     2020
4     2020
      ...
95    2020
96    2020
97    2020
98    2020
99    2020
Name: Exercício, Length: 100, dtype: int64

In [25]:
#Alterando várias colunas de uma vez
df.astype({
    'Exercício':'datetime64[ns]',
#     'Group Cód': int,
#     'Cód. Empresa': int,
     'PLoa': float
})

ValueError: could not convert string to float: '1.750.000'

In [31]:
df['PLoa'] = df['PLoa'].str.replace('.', '', inplace=True)

TypeError: replace() got an unexpected keyword argument 'inplace'